# **Homework**: Data talks club data engineering zoomcamp Data loading workshop

Hello folks, let's practice what we learned - Loading data with the best practices of data engineering.

Here are the exercises we will do

# 1. Use a generator

Remember the concept of generator? Let's practice using them to futher our understanding of how they work.

Let's define a generator and then run it as practice.

**Answer the following questions:**

- **Question 1: What is the sum of the outputs of the generator for limit = 5?**
- **Question 2: What is the 13th number yielded**

I suggest practicing these questions without GPT as the purpose is to further your learning.

# Question 1 --> 8.382332347441762
# Question 2 --> 3.605551275463989

In [12]:
def square_root_generator(limit):
    n = 1
    while n <= limit:
        yield n ** 0.5, n
        n += 1

# Example usage:
limit = 5
generator = square_root_generator(limit)

sum = 0
for sqrt_value,n in generator:
    print(f'square value of {n} = {sqrt_value}')
    sum += sqrt_value
    print(f'sum  of outputs of the generator for limit 5 = {sum}')


limit = 13
generator = square_root_generator(limit)

sum = 0
for sqrt_value,n in generator:
    print(f'square value of {n} = {sqrt_value}')
    sum += sqrt_value

square value of 1 = 1.0
sum  of outputs of the generator for limit 5 = 1.0
square value of 2 = 1.4142135623730951
sum  of outputs of the generator for limit 5 = 2.414213562373095
square value of 3 = 1.7320508075688772
sum  of outputs of the generator for limit 5 = 4.146264369941973
square value of 4 = 2.0
sum  of outputs of the generator for limit 5 = 6.146264369941973
square value of 5 = 2.23606797749979
sum  of outputs of the generator for limit 5 = 8.382332347441762
square value of 1 = 1.0
square value of 2 = 1.4142135623730951
square value of 3 = 1.7320508075688772
square value of 4 = 2.0
square value of 5 = 2.23606797749979
square value of 6 = 2.449489742783178
square value of 7 = 2.6457513110645907
square value of 8 = 2.8284271247461903
square value of 9 = 3.0
square value of 10 = 3.1622776601683795
square value of 11 = 3.3166247903554
square value of 12 = 3.4641016151377544
square value of 13 = 3.605551275463989

# 2. Append a generator to a table with existing data


Below you have 2 generators. You will be tasked to load them to duckdb and answer some questions from the data

1. Load the first generator and calculate the sum of ages of all people. Make sure to only load it once.
2. Append the second generator to the same table as the first.
3. **After correctly appending the data, calculate the sum of all ages of people.**

In [13]:
def people_1():
    for i in range(1, 6):
        yield {"ID": i, "Name": f"Person_{i}", "Age": 25 + i, "City": "City_A"}

for person in people_1():
    print(person)


def people_2():
    for i in range(3, 9):
        yield {"ID": i, "Name": f"Person_{i}", "Age": 30 + i, "City": "City_B", "Occupation": f"Job_{i}"}


for person in people_2():
    print(person)

{'ID': 1, 'Name': 'Person_1', 'Age': 26, 'City': 'City_A'}
{'ID': 2, 'Name': 'Person_2', 'Age': 27, 'City': 'City_A'}
{'ID': 3, 'Name': 'Person_3', 'Age': 28, 'City': 'City_A'}
{'ID': 4, 'Name': 'Person_4', 'Age': 29, 'City': 'City_A'}
{'ID': 5, 'Name': 'Person_5', 'Age': 30, 'City': 'City_A'}
{'ID': 3, 'Name': 'Person_3', 'Age': 33, 'City': 'City_B', 'Occupation': 'Job_3'}
{'ID': 4, 'Name': 'Person_4', 'Age': 34, 'City': 'City_B', 'Occupation': 'Job_4'}
{'ID': 5, 'Name': 'Person_5', 'Age': 35, 'City': 'City_B', 'Occupation': 'Job_5'}
{'ID': 6, 'Name': 'Person_6', 'Age': 36, 'City': 'City_B', 'Occupation': 'Job_6'}
{'ID': 7, 'Name': 'Person_7', 'Age': 37, 'City': 'City_B', 'Occupation': 'Job_7'}
{'ID': 8, 'Name': 'Person_8', 'Age': 38, 'City': 'City_B', 'Occupation': 'Job_8'}

# 3. Merge a generator

Re-use the generators from Exercise 2.

A table's primary key needs to be created from the start, so load your data to a new table with primary key ID.

Load your first generator first, and then load the second one with merge. Since they have overlapping IDs, some of the records from the first load should be replaced by the ones from the second load.

After loading, you should have a total of 8 records, and ID 3 should have age 33.

Question: **Calculate the sum of ages of all the people loaded as described above.**

# Solution: First make sure that the following modules are installed:

# 2. Append a generator to a table with existing data Solutions

In [14]:
#Install the dependencies
%%capture
!pip install dlt[duckdb]

In [16]:
import dlt

In [17]:
# to do: homework :)
## 2. Append a generator to a table with existing data
# define the pipeline
pipeline = dlt.pipeline(destination='duckdb', dataset_name='country')

# run the pipeline object with the first generator
info = pipeline.run(people_1(),
										table_name="persons",
										write_disposition="replace")

In [18]:
## import duckdb
import duckdb

In [19]:
## connect to duckdb
conn = duckdb.connect(f"{pipeline.pipeline_name}.duckdb")

In [20]:
conn.sql(f"SET search_path = '{pipeline.dataset_name}'")

In [21]:
persons = conn.sql("SELECT * FROM persons").df()
display(persons)

   id      name  age    city        _dlt_load_id         _dlt_id
0   1  Person_1   26  City_A  1707776326.4319808  g9ZbocqkYhOLrQ
1   2  Person_2   27  City_A  1707776326.4319808  /nPJunWe/wL/Xg
2   3  Person_3   28  City_A  1707776326.4319808  oAnxp1OX+iG+Cg
3   4  Person_4   29  City_A  1707776326.4319808  7tacY65xXXdCuQ
4   5  Person_5   30  City_A  1707776326.4319808  bxmgCbrdXEWhBw

In [22]:
## calculate the sum over all ages after loading the first generator
conn.sql("SELECT SUM(age) FROM persons")

┌──────────┐
│ sum(age) │
│  int128  │
├──────────┤
│      140 │
└──────────┘

In [23]:
### append the second generator to the same table
info = pipeline.run(people_2(),
										table_name="persons",
										write_disposition="append")

In [24]:
persons = conn.sql("SELECT * FROM persons").df()
display(persons)

    id      name  age    city        _dlt_load_id         _dlt_id occupation
0    1  Person_1   26  City_A  1707776326.4319808  g9ZbocqkYhOLrQ       None
1    2  Person_2   27  City_A  1707776326.4319808  /nPJunWe/wL/Xg       None
2    3  Person_3   28  City_A  1707776326.4319808  oAnxp1OX+iG+Cg       None
3    4  Person_4   29  City_A  1707776326.4319808  7tacY65xXXdCuQ       None
4    5  Person_5   30  City_A  1707776326.4319808  bxmgCbrdXEWhBw       None
5    3  Person_3   33  City_B  1707776609.4476075  Ou0QjE0vKqidmw      Job_3
6    4  Person_4   34  City_B  1707776609.4476075  BaIgNGGhMvxWGg      Job_4
7    5  Person_5   35  City_B  1707776609.4476075  +NoiYzjvgxn7BA      Job_5
8    6  Person_6   36  City_B  1707776609.4476075  dyI8Mmh1Xwr9MQ      Job_6
9    7  Person_7   37  City_B  1707776609.4476075  7FysoEhXOTynDQ      Job_7
10   8  Person_8   38  City_B  1707776609.4476075  CIyxAa20T4htSg      Job_8

In [25]:
conn.sql("SELECT SUM(age) FROM persons")

┌──────────┐
│ sum(age) │
│  int128  │
├──────────┤
│      353 │
└──────────┘

# Merge a generator solutions

In [26]:
## load the first generator into new table wiht replace
info_with_pk = pipeline.run(people_1(),
										table_name="persons_pk",
										write_disposition="replace",
                    primary_key = "ID")

In [28]:
conn.sql("SELECT * FROM persons_pk")

┌───────┬──────────┬───────┬─────────┬────────────────────┬────────────────┐
│  id   │   name   │  age  │  city   │    _dlt_load_id    │    _dlt_id     │
│ int64 │ varchar  │ int64 │ varchar │      varchar       │    varchar     │
├───────┼──────────┼───────┼─────────┼────────────────────┼────────────────┤
│     1 │ Person_1 │    26 │ City_A  │ 1707776972.5078042 │ kBhR7AmO9Oo3Cg │
│     2 │ Person_2 │    27 │ City_A  │ 1707776972.5078042 │ x3iQkCBGZKmuNA │
│     3 │ Person_3 │    28 │ City_A  │ 1707776972.5078042 │ RuL4XLiLumD5dA │
│     4 │ Person_4 │    29 │ City_A  │ 1707776972.5078042 │ GJEHISba9ANCJg │
│     5 │ Person_5 │    30 │ City_A  │ 1707776972.5078042 │ nHxDV7KWQf9Jkw │
└───────┴──────────┴───────┴─────────┴────────────────────┴────────────────┘

In [29]:
## load the second the second generator into new table with merge
info_with_pk = pipeline.run(people_2(),
										table_name="persons_pk",
										write_disposition="merge",
                    primary_key = "ID")

In [31]:
conn.sql("SELECT * FROM persons_pk order by id")

┌───────┬──────────┬───────┬─────────┬────────────────────┬────────────────┬────────────┐
│  id   │   name   │  age  │  city   │    _dlt_load_id    │    _dlt_id     │ occupation │
│ int64 │ varchar  │ int64 │ varchar │      varchar       │    varchar     │  varchar   │
├───────┼──────────┼───────┼─────────┼────────────────────┼────────────────┼────────────┤
│     1 │ Person_1 │    26 │ City_A  │ 1707776972.5078042 │ kBhR7AmO9Oo3Cg │ NULL       │
│     2 │ Person_2 │    27 │ City_A  │ 1707776972.5078042 │ x3iQkCBGZKmuNA │ NULL       │
│     3 │ Person_3 │    33 │ City_B  │ 1707777082.1094513 │ RkW8nBVNcowvrg │ Job_3      │
│     4 │ Person_4 │    34 │ City_B  │ 1707777082.1094513 │ wLpyUYo0iHvRlg │ Job_4      │
│     5 │ Person_5 │    35 │ City_B  │ 1707777082.1094513 │ SsjGNfenX5Dqgw │ Job_5      │
│     6 │ Person_6 │    36 │ City_B  │ 1707777082.1094513 │ +At0XnlxnJWclA │ Job_6      │
│     7 │ Person_7 │    37 │ City_B  │ 1707777082.1094513 │ 0F43pXepiy94YQ │ Job_7      │
│     8 │ Person_8 │    38 │ City_B  │ 1707777082.1094513 │ uqMMV65uis8SbA │ Job_8      │
└───────┴──────────┴───────┴─────────┴────────────────────┴────────────────┴────────────┘

In [32]:
conn.sql("SELECT sum(age) as sum_ages FROM persons_pk")

┌──────────┐
│ sum_ages │
│  int128  │
├──────────┤
│      266 │
└──────────┘

Questions? difficulties? We are here to help.
- DTC data engineering course channel: https://datatalks-club.slack.com/archives/C01FABYF2RG
- dlt's DTC cohort channel: https://dlthub-community.slack.com/archives/C06GAEX2VNX